### ISSUE TITLE
workflow run all environment when workflow run manually

### ISSUE THREAD

**Issue by kitsystemyou** [kitsystemyou/EnigmaticEcho#24]
now, when workflow run manually, workflow run all environment(silver, gold, red).
I want to solve this problem.

### Solution
1. divide workflow manually and schedule.
2. make common workflow file which execute the workflow with one environment.

common workflow
1. reusable workflow: https://docs.github.com/ja/actions/sharing-automations/reusing-workflows
2. composite action: https://docs.github.com/ja/actions/sharing-automations/creating-actions/creating-a-composite-action#creating-an-action-metadata-file

I select 2. because Reusable workflow do whole workflow.
I want to do the workflow with **one** environment.

**Comment by kitsystemyou** [comment]
secret doesn't work in composite action ...
https://github.com/kitsystemyou/EnigmaticEcho/actions/runs/13952789046

**Comment by kitsystemyou** [comment]
reusable workflow can use secret but it is a long definition code
like this

```
name: Generate and Post Image

on:
  workflow_call:
    inputs:
      prompt-preset:
        required: true
        type: string
        description: "Prompt preset to use (silver/gold/red)"
      needs-approval:
        required: true
        type: boolean
        description: "Whether this job needs approval"
      environment-name:
        required: false
        type: string
        description: "Environment name for approval"
        default: ""
    secrets:
      openai-api-key:
        required: true
      twitter-api-key:
        required: true
      twitter-api-secret:
        required: true
      twitter-access-token:
        required: true
      twitter-access-token-secret:
        required: true

jobs:
  generate-and-post:
    runs-on: ubuntu-latest
    environment: ${{ inputs.needs-approval && inputs.environment-name || '' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.openai-api-key }}
          TWITTER_API_KEY: ${{ secrets.twitter-api-key }}
          TWITTER_API_SECRET: ${{ secrets.twitter-api-secret }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.twitter-access-token }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.twitter-access-token-secret }}
          PROMPT_PRESET: ${{ inputs.prompt-preset }}
        run: python main.py
```

### Conclusion
divide jobs but don't divide workflow
