### ISSUE TITLE
Retry for github actions

### ISSUE THREAD

**Issue by kitsystemyou** [kitsystemyou/EnigmaticEcho#4]
e.g. https://github.com/kitsystemyou/EnigmaticEcho/actions/runs/12758403807

![Image](https://github.com/user-attachments/assets/3d784f3b-78a8-4be6-816d-7a11eaa47f5b)

other

- failed to generate image
- failed to send image 
  - for cloud storage
  - post each SNSs.

**Comment by kitsystemyou** [comment]
solution idea: https://zenn.dev/yuki_2021/articles/1e08334a4721d3
but i must think for `Environment` (when actions retry, whether if job get Environment info

**Comment by kitsystemyou** [comment]
from Claude

--- 
This error occurs when GitHub Actions is unable to fetch your repository due to server-side issues. The error codes 502 and 500 indicate server problems:

- 502 Bad Gateway: Indicates an invalid response from the GitHub servers
- 500 Internal Server Error: Indicates a server-side problem on GitHub's end

Here are potential solutions:

1. Temporary Solution:
   - Simply re-run the failed workflow
   - These errors are often temporary and resolve themselves

2. If the error persists:
   - Check GitHub's status page (https://www.githubstatus.com/) to see if there are any ongoing issues
   - Verify your repository URL is correct
   - Ensure your repository permissions are properly set up for GitHub Actions

3. Authentication-related fixes:
   ```yaml
   - uses: actions/checkout@v4
     with:
       token: ${{ secrets.GITHUB_TOKEN }}
   ```
   Make sure you're using the latest version of `actions/checkout`

4. If using self-hosted runners:
   - Clear the runner's cache
   - Verify network connectivity
   - Check if you can access GitHub from the runner machine

5. Repository-specific solutions:
   - Try with a shallower clone:
   ```yaml
   - uses: actions/checkout@v4
     with:
       fetch-depth: 1
   ```
   
   - Or with full history if needed:
   ```yaml
   - uses: actions/checkout@v4
     with:
       fetch-depth: 0
   ```

Since you're getting server errors (500, 502), this is most likely a temporary GitHub issue. I recommend:
1. Wait a few minutes
2. Check GitHub status page
3. Re-run the workflow
4. If the issue persists for several hours, contact GitHub support

---
